destination: ./_site/

url: "https://arfp.github.io" # site base hostname & protocol, e.g. http://example.com
baseurl: "" # site subpath, e.g. /blog

title: "ARFP" # site main title
slogan: "Kit Pédagogique"
description: Ressources et guides pour les formations DWWM et CDA<br /> disponibles sous license Creative Commons.

owner: ARFP
github: https://github.com/ARFP/
github_repo: https://github.com/ARFP/arfp.github.io/
linkedin: https://www.linkedin.com/company/arfp-crm-mulhouse/

street_address: 7 boulevard des nations
city: Mulhouse
zip_code: 68100
country: France
phone: 03 89 32 46 46


permalink: /articles/:categories/:title.html # posts permalink format

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

sass:
  style: compact
  sass_dir: _sass

markdown: kramdown
#kramdown:
#  parse_block_html: true

#collections
# collections_dir: content

collections:
  docs:
    output: true 
  guides:
    output: true 


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - 
    scope:
      path: "_docs"
    values:
      layout: "doc"
      type: doc
  - 
    scope:
      path: "_docs/algo"
    values:
      type: algo   
      image: /assets/img/banner-algo.jpg 
  - 
    scope:
      path: "_docs/dotnet"
    values:
      type: dotnet    
      image: /assets/img/banner-dotnet.jpg 
  - 
    scope:
      path: "_docs/php"
    values:
      type: php    
      image: /assets/img/banner-php.jpg 
  
  